-- Canada Medical Exams Requests Table
CREATE TABLE IF NOT EXISTS `canada_medical_exams_requests` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` varchar(50) NOT NULL,
  `reference_id` varchar(20) NOT NULL,
  `first_name` varchar(100) NOT NULL,
  `last_name` varchar(100) NOT NULL,
  `email` varchar(150) NOT NULL,
  `phone_area_code` varchar(10) DEFAULT NULL,
  `phone_number` varchar(20) NOT NULL,
  `address` text NOT NULL,
  `emergency_full_name` varchar(150) NOT NULL,
  `emergency_relationship` varchar(100) NOT NULL,
  `emergency_area_code` varchar(10) DEFAULT NULL,
  `emergency_phone_number` varchar(20) NOT NULL,
  `emergency_email` varchar(150) NOT NULL,
  `passport_file` varchar(255) NOT NULL,
  `cv_file` varchar(255) NOT NULL,
  `payment_proof_file` varchar(255) NOT NULL,
  `medical_report_form_file` varchar(255) NOT NULL,
  `payment_proof_validated` tinyint(1) DEFAULT 0,
  `ai_validation_result` text DEFAULT NULL,
  `status` enum('pending','under_review','approved','rejected') DEFAULT 'pending',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `reference_id` (`reference_id`),
  KEY `user_id` (`user_id`),
  KEY `status` (`status`),
  KEY `created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
