-- Francophonie Mobility (Canada Work Visa) applications
CREATE TABLE IF NOT EXISTS `francophonie_mobility_applications` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` varchar(80) NOT NULL,
  `reference_id` varchar(24) NOT NULL,
  `first_name` varchar(100) NOT NULL,
  `last_name` varchar(100) NOT NULL,
  `email` varchar(150) NOT NULL,
  `phone_area_code` varchar(10) DEFAULT NULL,
  `phone_number` varchar(20) NOT NULL,
  `date_of_birth` date DEFAULT NULL,
  `passport_number` varchar(64) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `age` tinyint(3) unsigned DEFAULT NULL,
  `nationality` varchar(100) NOT NULL,
  `country_of_residence` varchar(100) NOT NULL,
  `profession` varchar(200) NOT NULL,
  `years_experience` varchar(20) DEFAULT NULL,
  `highest_degree` varchar(200) NOT NULL,
  `field_of_study` varchar(200) NOT NULL,
  `university_name` varchar(255) NOT NULL,
  `country_of_study` varchar(100) NOT NULL,
  `graduation_year` varchar(10) DEFAULT NULL,
  `other_certifications` text DEFAULT NULL,
  `french_level` enum('beginner','intermediate','advanced','fluent') NOT NULL,
  `french_tef` tinyint(1) NOT NULL DEFAULT 0,
  `french_tcf` tinyint(1) NOT NULL DEFAULT 0,
  `french_professional` enum('yes','no') NOT NULL,
  `english_level` enum('beginner','intermediate','advanced','fluent') NOT NULL,
  `english_toefl` tinyint(1) NOT NULL DEFAULT 0,
  `english_ielts` tinyint(1) NOT NULL DEFAULT 0,
  `english_professional` enum('yes','no') NOT NULL,
  `has_wes` enum('yes','no') NOT NULL,
  `job_offer` varchar(120) DEFAULT NULL,
  `cv_file` varchar(255) NOT NULL,
  `french_cert_file` varchar(255) NOT NULL,
  `english_cert_file` varchar(255) DEFAULT NULL,
  `academic_docs_file` varchar(255) NOT NULL,
  `admin_notes` text DEFAULT NULL,
  `approval_package_sent_at` datetime DEFAULT NULL,
  `status` enum('pending','under_review','approved','rejected') NOT NULL DEFAULT 'pending',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `reference_id` (`reference_id`),
  KEY `user_id` (`user_id`),
  KEY `status` (`status`),
  KEY `email` (`email`),
  KEY `created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `francophonie_mobility_status_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `application_id` int(11) NOT NULL,
  `old_status` varchar(32) DEFAULT NULL,
  `new_status` varchar(32) NOT NULL,
  `admin_id` int(11) DEFAULT NULL,
  `note` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `application_id` (`application_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
